### PR TITLE
Fixing compilation without DDalphaAMG

### PR DESCRIPTION
**Pull request by sbacchio**
In response to issue #346.

@kostrzewa @urbach What do you think about this solution?

### CODE REVIEW

**Comment by kostrzewa** [comment]
@urbach could you take a look at this please? I'm okay with the solution proposed by @sbaccio.

**Comment by kostrzewa** [comment]
I might, at some point in the future, provide a pull-request which moves the mg parameters out of DDalphaAMG and into a global context, thereby providing a uniform parameter set for different MG implementations, as far as possible. (The set of paramters might be extended in the future).

**Comment by urbach** [comment]
yes, this is fine with me, should I merge it in?

**Comment by kostrzewa** [comment]
Sure, please go ahead. Thanks!

**Pull request merged**
