### PR TITLE
remove legacy GPU support

### PR DESCRIPTION
**Pull request by kostrzewa**
The presence of both legacy GPU code and the QUDA interface is confusing, especially since the former is completely unmaintained. This PR removes the legacy code completely.

### CODE REVIEW

**Comment by kostrzewa** [comment]
@Marcogarofalo @simone-romiti I think I got all remnants of the legacy GPU code, it would be great if you could take a look, however.

@urbach Do you agree with the complete removal of the legacy GPU code?

**Comment by urbach** [comment]
> @Marcogarofalo @simone-romiti I think I got all remnants of the legacy GPU code, it would be great if you could take a look, however.
> 
> @urbach Do you agree with the complete removal of the legacy GPU code?

definitly!

**Comment by kostrzewa** [comment]
@Marcogarofalo @simone-romiti did you have a chance yet to check if I've forgotten to remove something?

**Comment by Marcogarofalo** [comment]
I checked this version and it works. Maybe there is still some legacy file or line that can be eliminated in the future. I will suggest proceeding with the merge.

**Pull request merged**
