### PR TITLE
fixed missing parameters to measure_gauge_action and read_gauge_field

### PR DESCRIPTION
**Pull request by urbach**
somehow these typos sneaked into master...

### CODE REVIEW

**Comment by urbach** [comment]
this is very quick to check. Without these changes the code does not compile.

**Comment by kostrzewa** [comment]
I submitted a pull-request for this a few weeks ago. We changed the signature of the two functions after offline_measurement was pulled in and forgot to change offline_measuremet.

**Comment by kostrzewa** [comment]
See #296

**Comment by urbach** [comment]
okay, sorry, I overlooked #296, merged this now...

**Pull request closed without merging**
