### PR TITLE
Quda work merge master

### PR DESCRIPTION
**Pull request by kostrzewa**
Just getting quda_work synchronized with master on a few commits. PR to check if nothing nasty happens.

### CODE REVIEW

**Comment by kostrzewa** [comment]
This compiles fine for me. @simone-romiti c

**Comment by kostrzewa** [comment]
Tested compilation on Bender, seems to work fine.

**Comment by kostrzewa** [comment]
Compilation on LUMI-G continues to function. This leaves only Marconi 100 with a question mark.

**Comment by simone-romiti** [comment]
For me it works also on Marconi 100

**Comment by kostrzewa** [comment]
Perfect, thanks a lot for the tests.

**Pull request merged**
