### PR TITLE
move checking for CUDA or HIP libraries outside of the QUDA config block

### PR DESCRIPTION
**Pull request by kostrzewa**
This seems to work for me to link QUDA with CUDA. I haven't tried QUDA with HIP yet.

### CODE REVIEW

**Comment by kostrzewa** [comment]
I've updated https://notes.desy.de/HJyYWNj1Rb-G7-ojjqDNWQ?view#Compiling-tmLQCD and with this, I can compile and link a version of hmc_tm which at least starts up. It then fails for yet unknown reasons with segfaults in MPI functions -> #jsc-amd-mpi channel in the Hackathon JuChat

**Comment by kostrzewa** [comment]
See `/p/project/fssh/kostrzewa2/build/dc-mi200/stage_2022/gcc_11_2_0/openmpi_4_1_2/tmLQCD.quda_work_add_actions_different_backends` if you can acces it.

**Comment by simone-romiti** [comment]
I've done a test linking with CUDA on marconi100 and run a successful job.

**Comment by kostrzewa** [comment]
Perfect, thanks. I can also confirm that it works on dc-mi200

**Pull request merged**
