### PR TITLE
Replace MPI macro definition

### PR DESCRIPTION
**Pull request by urbach**
partly solves #314

### CODE REVIEW

**Comment by urbach** [comment]
what I did was to replace

    "ifdef[blank]* MPI" -> "ifdef TM_USE_MPI"
    "ifndef[blank]* MPI" -> "ifndef TM_USE_MPI"
    "defined[blank]* MPI" -> "defined TM_USE_MPI"

and some manual replacements in the GPU directory. And of course corresponding changes to configure.in and config.h.in

**Comment by kostrzewa** [comment]
Conflicts from #323

**Comment by urbach** [comment]
fixed!

--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
Looks okay to me, checked ```grep MPI *.c *.h */*.c */*.h | grep def | less```

**Comment by kostrzewa** [comment]
I'll merge this now. Propagating the changes to the interleaved branches will be a little bit tricky because of the three loop halfspinor hopping matrix, which will likely have to be adjusted manually.

**Comment by urbach** [comment]
True,  didn't think that far yet

On 22 May 2016 14:13:59 CEST, Bartosz Kostrzewa <notifications@github.com> wrote:
>I'll merge this now. Propagating the changes to the interleaved
>branches will be a little bit tricky because of the three loop
>halfspinor hopping matrix, which will likely have to be adjusted
>manually.
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/etmc/tmLQCD/pull/322#issuecomment-220829188

Carsten Urbach, www.carsten-urbach.eu

**Comment by urbach** [comment]
so, indeed, the file `halfspinor_body.c` is causing problems in the interleaving branch. But it seems to me this can be fixed by just doing the replacements of the macros again in this file? What do you think @kostrzewa

**Comment by urbach** [comment]
see my branch testMerge which originates from the interleaved branch. Do you think `halfspinor_body.c` is okay like this?

**Comment by kostrzewa** [comment]
@urbach 
> But it seems to me this can be fixed by just doing the replacements of the macros again in this file?

I agree, the "natural" way to resolve the merge conflict would be to choose the "ours" side of the merge for the two halfspinor bodies (64 and 32) and manually replace all mentions ```MPI``` and ```OMP```. 

However, ```halfspinor_body.c``` is fine (did a side-by-side diff, only differences are the macros), but ```halfspinor_body_32.c``` in your INDTC branch is missing the overlapping structure. When Florian re-implemted the 32 bit hopping matrix, he took a slightly different approach as well, which I preserved. (the main difference are some prefetches)

See here: https://github.com/kostrzewa/tmLQCD/blob/mixed_cg_merge_hmc_INDTC/operator/halfspinor_body_32.c

**Comment by urbach** [comment]
so, which version of `halfspinor_body_32.c` I should start from then?

**Comment by kostrzewa** [comment]
I think if you ```checkout``` the one from my mixed_cg_merge_hmc_INDTC branch into your testMerge branch and do the replacements, that should be fine. That's the version we have been using all this time.

**Comment by urbach** [comment]
okay, done...

**Comment by kostrzewa** [comment]
Okay, thanks a lot!

**Comment by urbach** [comment]
so, I'll merge this back to my interleaving branch, I guess...

**Comment by urbach** [comment]
done

**Pull request merged**
